"""Rain over land for the rain bar (core/land_rain.py, 2026-09-26)."""
from datetime import datetime, timezone

from core import land_rain as lr

# Excerpts of real public advisories (NOAA text, public domain).
NOLO_23A = """<html><body><pre>
BULLETIN
Hurricane Nolo Intermediate Advisory Number 23A
NWS Central Pacific Hurricane Center Honolulu HI   EP152026
Issued by NWS National Hurricane Center Miami FL
200 AM HST Sat Sep 26 2026

HAZARDS AFFECTING LAND
----------------------
WIND: Tropical storm conditions are occurring in portions of the
warning area in areas of steep terrain.

RAINFALL: For the eastern and southern portions of the Big Island,
Nolo will produce rainfall totals of 8 to 12 inches with maximum
amounts of 16 inches. This rainfall could produce significant,
life-threatening flooding and mudslides, especially in areas of
steep terrain.

For the western portions of the Big Island, rainfall totals of 1 to
3 inches with maximum amounts of 6 inches are expected. For eastern
Maui, rainfall totals of 4 to 6 inches with maximum amounts of 8
inches are expected. Life-threatening flooding and mudslides are
possible, especially in areas of high terrain.

Across the remainder of the Hawaiian Islands, maximum rainfall
totals of 1 to 2 inches are expected.

For a complete depiction of forecast rainfall associated with Nolo,
please see the National Weather Service Storm Total Rainfall Graphic
available at <a href='https://www.hurricanes.gov/graphics_cp2.shtml?rainqpf'>hurricanes.gov/graphics_cp2.shtml?rainqpf</a>

STORM SURGE: The combination of a dangerous storm surge and the tide
will cause normally dry areas near the coast to be flooded.
</pre></body></html>"""

POLO_23 = """Hurricane Polo Advisory Number 23
NWS National Hurricane Center Miami FL       EP172026

RAINFALL: Polo is expected to produce rainfall totals of 4 to 8
inches (100 to 200 mm) with maximum amounts of 10 inches (250 mm)
across portions of Baja California Sur. This rainfall may produce
life-threatening flooding and mudslides, especially in areas of
steep terrain.

SURF: Swells generated by Polo are affecting portions of the coast.
"""

NO_RAIN = """Tropical Storm Gonzalo Advisory Number 9
NWS National Hurricane Center Miami FL       AL072026

HAZARDS AFFECTING LAND
----------------------
None.
"""


def test_parse_nolo_areas_and_impact():
    t = lr.advisory_text(NOLO_23A)
    assert lr.issuing_center(t) == "CPHC"                  # not the backup NHC byline
    assert lr.advisory_label(t) == "Advisory 23A"
    p = lr.parse_rainfall(t)
    assert [(a["area"], a["lo_in"], a["hi_in"], a["max_in"]) for a in p["areas"]] == [
        ("eastern and southern portions of the Big Island", 8, 12, 16),
        ("western portions of the Big Island", 1, 3, 6),
        ("eastern Maui", 4, 6, 8),
        ("remainder of the Hawaiian Islands", 1, 2, 2),
    ]
    assert p["impact"].startswith("This rainfall could produce significant, life-threatening flooding")
    assert "STORM SURGE" not in lr.rainfall_section(t)     # section stops at the next hazard


def test_parse_polo_ignores_mm_and_finds_trailing_area():
    p = lr.parse_rainfall(lr.advisory_text(POLO_23))
    assert p["areas"] == [{"area": "portions of Baja California Sur",
                           "lo_in": 4.0, "hi_in": 8.0, "max_in": 10.0}]


def test_no_rainfall_section_means_no_bar():
    t = lr.advisory_text(NO_RAIN)
    res = lr.build({"center": "NHC", "label": "Advisory 9", "issued_utc": None,
                    **lr.parse_rainfall(t)}, [], None)
    assert res["available"] and not res["show"] and res["source"] == "advisory"


def test_build_advisory_bar_text():
    t = lr.advisory_text(NOLO_23A)
    adv = {"center": "CPHC", "label": "Advisory 23A", "issued_utc": "2026-09-26T12:00:00Z",
           **lr.parse_rainfall(t)}
    pts = [{"name": "Hilo, HI", "lat": 19.72, "lon": -155.08, "dist_km": 250, "total_in": 5.39},
           {"name": "Naalehu, HI", "lat": 19.06, "lon": -155.59, "dist_km": 180, "total_in": 6.05}]
    res = lr.build(adv, pts, "nws")
    assert res["show"] and res["level"] == "EXTREME" and res["max_in"] == 16
    assert res["score_text"] == "Rain up to 16 in —"
    assert res["text"].startswith(
        "Extreme rain forecast: eastern and southern portions of the Big Island 8–12 in (locally 16 in); "
        "eastern Maui 4–6 in (locally 8 in); western portions of the Big Island 1–3 in (locally 6 in).")
    assert "remainder of the Hawaiian Islands" not in res["text"]     # < 3 in areas dropped
    assert "NWS forecast, next 3 days: Naalehu, HI 6 in, Hilo, HI 5.4 in." in res["text"]
    assert res["text"].endswith("— CPHC Advisory 23A")


def test_directive_sentences_never_become_the_impact_line():
    t = ("RAINFALL: Rainfall totals of 10 to 15 inches are expected across Puerto Rico. "
         "Residents should follow the advice of local officials regarding flooding.\n\nSURF: x")
    p = lr.parse_rainfall(t)
    assert p["impact"] is None and p["areas"][0]["area"] == "Puerto Rico"


def test_levels():
    assert [lr.level_for(v) for v in (3.9, 4, 8, 15, 25, None)] == [
        None, "ELEVATED", "HIGH", "EXTREME", "HISTORIC", None]


def test_model_points_bar_carries_attribution_and_caveat():
    pts = [{"name": "Hualien", "lat": 24.0, "lon": 121.6, "dist_km": 90, "total_in": 7.24},
           {"name": "Yilan", "lat": 24.75, "lon": 121.75, "dist_km": 120, "total_in": 5.1},
           {"name": "Taipei", "lat": 25.03, "lon": 121.56, "dist_km": 160, "total_in": 0.4}]
    res = lr.build(None, pts, "model")
    assert res["show"] and res["level"] == "ELEVATED" and res["source"] == "model"
    assert "up to 7.2 in at Hualien, 5.1 in at Yilan over the next 3 days" in res["text"]
    assert "Open-Meteo.com (CC BY 4.0)" in res["text"] and lr.MODEL_CAVEAT in res["text"]
    quiet = lr.build(None, [{"name": "Naha", "lat": 26.2, "lon": 127.7, "dist_km": 50, "total_in": 1.0}], "model")
    assert quiet["available"] and not quiet["show"]


def test_select_places_radius_order_and_antimeridian():
    track = [{"hour": 0, "lat": -17.0, "lon": 179.0}, {"hour": 24, "lat": -18.0, "lon": -178.0}]
    places = [(-17.8, 178.4, "Suva"), (-18.1, -178.3, "Lau Group"),
              (-13.8, -171.8, "Apia"), (-17.8, 178.4, "Suva")]
    hits = lr.select_places(track, places, radius_km=400)
    names = [h["name"] for h in hits]
    assert names == sorted(names, key=lambda n: {h["name"]: h["dist_km"] for h in hits}[n])
    assert set(names) == {"Suva", "Lau Group"}                # Apia too far, Suva once
    beyond = [{"hour": 0, "lat": 17, "lon": -155.3}, {"hour": 96, "lat": 30, "lon": -150}]
    assert lr.select_places(beyond, [(29.0, -150.5, "far")], horizon_h=72) == []


def test_sum_nws_qpf_prorates_edges():
    now = datetime(2026, 9, 26, 3, 0, tzinfo=timezone.utc)
    vals = [{"validTime": "2026-09-26T00:00:00+00:00/PT6H", "value": 25.4},   # half inside
            {"validTime": "2026-09-26T06:00:00+00:00/PT6H", "value": 50.8},
            {"validTime": "2026-09-29T00:00:00+00:00/PT6H", "value": 25.4},   # half inside (ends +75 h)
            {"validTime": "2026-09-29T06:00:00+00:00/P1D", "value": 999},     # beyond
            {"validTime": "2026-09-26T12:00:00+00:00/PT6H", "value": None}]
    assert lr.sum_nws_qpf(vals, now) == 3.0
    assert lr.sum_nws_qpf([], now) is None


def test_sum_hourly_window():
    now = datetime(2026, 9, 26, 5, 40, tzinfo=timezone.utc)
    times = [f"2026-09-26T{h:02d}:00" for h in range(4, 8)]
    assert lr.sum_hourly(times, [25.4, 25.4, 25.4, None], now) == 2.0          # 05:00 and 06:00


def test_us_boxes():
    assert lr.is_us_place(19.72, -155.08) and lr.is_us_place(13.47, 144.75)
    assert lr.is_us_place(18.4, -66.06) and not lr.is_us_place(24.0, 121.6)
